Add DownloadWithCustom
DataDog/go-tuf pull request #5
Opened 2021-07-19 12:07 UTC by raphaelgavache

Return a downloaded file matching custom

2021-07-28 14:57 UTC, hosseinsia commented on client/client.go
> +func (c *Client) DownloadWithCustom(name string, dest Destination) (err error, custom *json.RawMessage) {
My understanding is that custom is downloaded anyway. Does it make sense to add a method to Client instead, say getCustomMetadata and people who need it call that after the download?

2021-08-04 17:33 UTC, trishankatdatadog requested changes

2021-08-04 17:33 UTC, trishankatdatadog commented on client/client.go
> +func (c *Client) DownloadWithCustom(name string, dest Destination) (err error, custom *json.RawMessage) {
Is there any reason to split this function? Why not just make it the default behaviour?

2021-08-04 17:34 UTC, trishankatdatadog commented on client/client.go
> +func (c *Client) DownloadWithCustom(name string, dest Destination) (err error, custom *json.RawMessage) {
Actually, on second thought, so as not to break backwards-compatibility with existing clients that depend on this API, we should make DownloadWithCustom an entirely new function, as you have, but not have Download call it.

2021-10-05 17:44 UTC, closed without merging