Hosseinsia/updatetherootrole
DataDog/go-tuf pull request #8
Opened 2021-07-28 00:03 UTC by hosseinsia

Update the root according to 
https://theupdateframework.github.io/specification/v1.0.19/index.html#load-trusted-root

2021-07-28 00:04 UTC, hosseinsia commented
Fixtures are generated using this repo:
https://github.com/DataDog/tuf-fixtures

2021-07-30 21:01 UTC, trishankatdatadog requested changes
Will send more comments later, but this is really getting into shape, thanks!

2021-07-30 21:01 UTC, trishankatdatadog commented on client/client.go
> +		keyIDs := make([]string, 0, len(c.db.GetRole("timestamp").KeyIDs))
```suggestion
		keyIDs := make([]string, 0, len(c.db.GetRole(role).KeyIDs))
```

2021-07-30 21:03 UTC, trishankatdatadog commented on client/client.go
> +	getKeyIDs := func(role string) []string {
```suggestion
	getKeyIDs := func(rolename string) []string {
```

2021-08-24 10:00 UTC, lebauce commented on verify/errors.go
> +	return fmt.Sprintf("version %d does not match the extepcted version %d", e.Given, e.Expected)
s/extepcted/expected/

2021-08-24 10:01 UTC, lebauce commented on verify/verify.go
> +	// Note: If verification fails, then we wont attemp to unmarshal
s/attemp/attempt/

2021-08-24 10:02 UTC, lebauce commented on verify/verify.go
> +	if verifyErr != nil {
return verifyErr

2021-08-24 11:06 UTC, hosseinsia commented
This is an abandoned PR. We decided to update the go-tuf upstream now. Please review this instead:
https://github.com/theupdateframework/go-tuf/pull/143

2021-08-24 11:06 UTC, closed without merging